import Navbar from "@/app/components/Navbar";
import "./globals.css";
import "font-awesome/css/font-awesome.min.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
